default_platform(:android)

platform :android do
  desc "Lane for Android firebase Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:558040243904:android:968af3ec90f863434a9725",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      groups: "qc-group",
      release_notes: "New release for testing"
    )

  end
end
